// 列出所有的 动作名称
export const REQUEST_QUESTION_LIST = 'REQUEST_QUESTION_LIST';

export const CREATE_NEW_NAIRE = 'CREATE_NEW_NAIRE';
export const EDIT_NAIRE = 'EDIT_NAIRE';
export const SAVE_NEW_NAIRE = 'SAVE_NEW_NAIRE';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const DEL_QUESTION = 'DEL_QUESTION';
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
export const DEL_OPTION = 'DEL_OPTION';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_RATIO = 'UPDATE_RATIO';
export const UPDATE_ATTACH = 'UPDATE_ATTACH';
export const UPDATE_INTRO = 'UPDATE_INTRO';
export const UPDATE_DEADLINE = 'UPDATE_DEADLINE';
export const UPDATE_AREAS = 'UPDATE_AREAS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_NTYPE = 'UPDATE_NTYPE';
export const UPDATE_UPLOADFILE = 'UPDATE_UPLOADFILE';
export const CHANGE_NAIRE_STATUS = 'CHANGE_NAIRE_STATUS';
export const USER_LOGIN = 'USER_LOGIN';
export const LOG_OUT = 'LOG_OUT';
